spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: ${MP_DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MP_DB_USERNAME}
    password: ${MP_DB_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  jackson:
    default-property-inclusion: non_null # null 인경우 필드 생성하지않음

  springfox:
    documentation:
      swagger-ui:
        base-url: /api

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_ID}
            client-secret: ${GITHUB_SECRET}
            scope: name,email
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope: email,profile



cloud:
  aws:
    s3:
      bucket: mp-static-file
    credentials:
      access-key: ${MP_AWS_ACCESS_KEY}
      secret-key: ${MP_AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace



logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR




server:
  port: 8081


env:
  port: 8081
  fport: 3000
