name: sub-branch

on:
  push:
    branches: ['fe-demo']
  pull_request:
    branches: ['fe-demo']

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: mv dir
        run: cd webapp
        shell: bash

      - name: Setting .env
        run: |
          echo "REACT_APP_SERVER_API=${{secrets.REACT_APP_SERVER_API}}" >> .env
          cat .env

      - name: npm Install
        run: npm install

      - name: npm build
        run: npm run build-demo

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FE_DEMO_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FE_DEMO_AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./build s3://conect-demo
