# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: REACT-BUILD

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

defaults:
  run:
    working-directory: ./webapp

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      working-directory: ./webapp

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: npm Install
        run:
          npm install
          npm build

      - name: zip create
        run: zip -qq -r ./build-fe.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}}

        run: |
          aws s3 cp --region ap-northeast-2 ./build-fe.zip s3://conect-react/mp/build-fe.zip

      - name: Deploy
        run: aws deploy create-deployment
          --application-name mp-react
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name MP-Group
          --s3-location bucket=conect-react,key=mp/build-fe.zip,bundleType=zip






